---
title: ""
---


### Articles scientifiques - Peer-reviewed journal articles

Forthcoming. Candidate Authenticity: "To thine own self be true". Political Behavior. Avec/With Dieter Stiers, Jac Larner, John Kenny, Sofia Breitenstein Gomis & Michael Lewis-Beck.

2017. [About time: age, period, and cohort effects on support for Quebec sovereignty](https://onlinelibrary.wiley.com/doi/pdf/10.1111/nana.12378). Nations and Nationalism. Avec/With Ruth Dassonneville & Jean‐François Godbout.


### Chapitre d'ouvrage collectif - Book chapter

2018. [L'analyse des scrutins parlementaires](https://www.larciergroup.com/fr/traite-d-etudes-parlementaires-2018-9782802760481.html). Dans/In Olivier Rozenberg & Eric Thiers, Traité d'études parlementaires, coll. Etudes parlementaires, Bruxelles: Larcier. Avec/With Jean-François Godbout.

### Texte d'opinion - Op-ed article

2017. [Quebec’s ethnic nationalism in perspective](http://policyoptions.irpp.org/magazines/february-2017/quebecs-ethnic-nationalism-in-perspective/). Policy Options. Avec Alexie Labelle.
