---
title: ''
---

## Ateliers R - R Workshops

Je suis disponible pour enseigner des ateliers d'introduction au langage R. Si vous voulez apprendre vous-même, je rends aussi accessibles mes notes de cours: [PDF](documentation/ateliers-r.pdf); [HTML](documentation/ateliers-r.html).

I am available to teach Intro to R workshops. If you would rather learn by yourself, my workshop notes are available here (in French only): [PDF](documentation/ateliers-r.pdf); [HTML](documentation/ateliers-r.html).

## Méthodes quantitatives - Quantitative Methods 

J'ai enseigné le cours Méthodes quantitatives d'analyse (POL 2809), un cours de niveau baccalauréat à l'Université de Montréal. C'est un véritable plaisir pour moi d'enseigner, et j'espère pouvoir être utile en rendant disponible plubliquement mon plan de cours, les présentations visuelles que j'ai utilisées en classe et certaines idées d'activités pédagogiques (à venir). N'hésitez pas à me contacter pour toute question!

[Plan de cours](documentation/syllabus.pdf): 

- [Statistiques descriptives](documentation/descriptive.pdf)
- [Introduction à la régression linéaire](documentation/ols.pdf)
- [Régression: la signification statistique](documentation/ols-signif.pdf)
- [Régression multiple](documentation/ols-multiple.pdf)
- [Régression: suite et fin](documentation/ols-end.pdf)
- [Problème fondamental de l'inférence causale](documentation/causalinf.pdf)
- [Graphiques orientés acycliques](documentation/goa.pdf)
- [Biais](documentation/biais.pdf)
- Méthodes expérimentales
- Méthodes quasi-expérimentales
- Visualisation de données

I taught an undergraduate-level class in Quantitative Methods (POL 2809) at the University of Montreal in the Fall of 2019. Teaching is one of the rewarding things I do for a living, and I hope to be useful by making publicly available my syllabus, the slides I used in class, and a few ideas for in-class activities. Contact me if you have any questions! The documentation is in French only but stay tuned for the English version.




      